'use strict';

// مفقود — نموذج PWA عربي. البيانات والحسابات هنا محلية على الجهاز.
const GOVERNORATES=['أمانة العاصمة','أبين','عدن','البيضاء','الجوف','الحديدة','الضالع','المحويت','المهرة','عمران','ذمار','ريمة','شبوة','صعدة','صنعاء','تعز','لحج','مأرب','حجة','حضرموت','إب','سقطرى'];
const SEED_REPORTS=[
 {id:'seed-1',title:'هاتف جوال أسود',type:'lost',icon:'📱',governorate:'عدن',city:'المنصورة',date:'منذ ساعتين',description:'هاتف أسود بغطاء شفاف، فُقد بالقرب من سوق المنصورة. لمن عثر عليه نرجو التواصل.',owner:'أحمد',phone:'',photo:'',category:'إلكترونيات',mine:false},
 {id:'seed-2',title:'مفتاح سيارة',type:'found',icon:'🔑',governorate:'تعز',city:'وسط المدينة',date:'منذ ٤ ساعات',description:'تم العثور على مفتاح سيارة قرب الشارع الرئيسي. يرجى وصف العلامة المميزة للتأكد.',owner:'مستخدم مفقود',phone:'',photo:'',category:'مفاتيح',mine:false},
 {id:'seed-3',title:'محفظة بنية',type:'found',icon:'👛',governorate:'أمانة العاصمة',city:'حي النخيل',date:'منذ ٦ ساعات',description:'محفظة بنية تحتوي على بطاقات. لا نعرض تفاصيلها حفاظاً على الخصوصية.',owner:'مستخدم مفقود',phone:'',photo:'',category:'مقتنيات شخصية',mine:false},
 {id:'seed-4',title:'حقيبة يد صغيرة',type:'lost',icon:'👜',governorate:'حضرموت',city:'المكلا',date:'أمس',description:'حقيبة صغيرة لونها كحلي فُقدت في السوق القديم.',owner:'مستخدم مفقود',phone:'',photo:'',category:'حقائب',mine:false}
];
const safeRead=(key,fallback)=>{try{const x=localStorage.getItem(key);return x?JSON.parse(x):fallback}catch{return fallback}};
let reports=safeRead('mafqood.reports',SEED_REPORTS);
if(!Array.isArray(reports))reports=SEED_REPORTS;
reports=reports.map(r=>({...r,governorate:r.governorate||'عدن',city:r.city||r.area||'',description:r.description||r.desc||'',owner:r.owner||'مستخدم مفقود',phone:r.phone||'',photo:r.photo||'',category:r.category||'مقتنيات شخصية',date:r.date||'اليوم',mine:Boolean(r.mine)}));
let user=safeRead('mafqood.user',null);
if(typeof user==='string')user={name:user,email:''};
let favorites=safeRead('mafqood.favorites',[]);
let screen=user?'home':'welcome', lastScreen='home', filterType='الكل', searchQuery='', selectedGovernorate='كل اليمن', selectedReport=null, draftType='lost', authMode='login', chatTarget='support', chatMessages=safeRead('mafqood.chat',[]), noticeTimer;
const view=document.getElementById('view');
const nav=document.querySelector('.bottom-nav');
const header=document.querySelector('.topbar');
const escapeHTML=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function persist(){try{localStorage.setItem('mafqood.reports',JSON.stringify(reports));localStorage.setItem('mafqood.favorites',JSON.stringify(favorites));localStorage.setItem('mafqood.chat',JSON.stringify(chatMessages));}catch{notify('مساحة التخزين ممتلئة؛ احذف صوراً أو بلاغات قديمة.')}}
function notify(message){const el=document.getElementById('toast');el.textContent=message;el.classList.add('show');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>el.classList.remove('show'),2600)}
function pageHeader(title,back='home'){return `<div class="page-title"><button class="back" data-go="${escapeHTML(back)}" aria-label="رجوع">›</button><h1>${escapeHTML(title)}</h1><span></span></div>`}
function labelType(type){return type==='lost'?'مفقود':'موجود'}
function imageBlock(r,small=false){return r.photo?`<img class="item-art-photo ${small?'small':''}" src="${r.photo}" alt="صورة ${escapeHTML(r.title)}">`:`<div class="item-art ${small?'small':''}">${escapeHTML(r.icon||'📦')}</div>`}
function reportCard(r){return `<article class="item-card" data-item="${escapeHTML(r.id)}" tabindex="0"><div>${imageBlock(r,true)}</div><div class="item-info"><b>${escapeHTML(r.title)}</b><p>${escapeHTML(r.city||'')}، ${escapeHTML(r.governorate||'')}</p><div class="item-foot"><span class="badge ${r.type}">${labelType(r.type)}</span><span>• ${escapeHTML(r.date||'')}</span></div></div><span class="arrow">‹</span></article>`}
function showScreen(next){lastScreen=screen;screen=next;render()}
function goTab(tab){screen=tab;document.querySelectorAll('.nav-item').forEach(btn=>btn.classList.toggle('active',btn.dataset.tab===tab));render()}
function homePage(){const matching=reports.filter(r=>(filterType==='الكل'||(filterType==='مفقودات'?r.type==='lost':r.type==='found'))&&(selectedGovernorate==='كل اليمن'||r.governorate===selectedGovernorate)&&(`${r.title} ${r.city} ${r.governorate} ${r.description}`.includes(searchQuery)));return `<section class="screen"><p class="greeting">مرحباً ${escapeHTML(user?.name||'بك')} 👋</p><h1 class="headline">خلّينا نساعد بعض</h1><label class="searchbar"><span class="glass">⌕</span><input id="homeSearch" placeholder="ابحث عن بلاغ أو مدينة..." value="${escapeHTML(searchQuery)}"><span>⚲</span></label><div class="hero-grid"><button class="hero-card lost" data-action="create-lost"><span class="emoji">🎒</span><b>فقدت شيئاً</b><small>أنشئ بلاغاً عن شيء مفقود</small></button><button class="hero-card found" data-action="create-found"><span class="emoji">🔎</span><b>وجدت شيئاً</b><small>ساعد صاحبه على استعادته</small></button></div><div class="callout" data-action="search"><span class="circle">⌕</span><span><b>ابحث في البلاغات</b><small>تصفّح المفقودات والموجودات في اليمن</small></span><span class="arrow">‹</span></div><div class="section-head"><h2>أحدث البلاغات</h2><button class="link-btn" data-action="search">عرض الكل</button></div><div class="filters">${['الكل','مفقودات','موجودات'].map(x=>`<button class="chip ${filterType===x?'active':''}" data-filter="${x}">${x}</button>`).join('')}</div><div class="cards">${matching.slice(0,6).map(reportCard).join('')||'<div class="empty">لا توجد نتائج. جرّب تغيير البحث أو أضف بلاغاً.</div>'}</div><div class="dev-footer">من تطوير المهندس أحمد المشألي · المشألي تك</div></section>`}
function welcomePage(){return `<section class="screen welcome"><div class="welcome-mark">📍</div><h1>مفقود</h1><p class="welcome-tagline">لأن كل شيء مهم<br>قد يعود إليك</p><div class="welcome-bottom"><p>منصة تساعد أهل اليمن في الإبلاغ عن المفقودات والموجودات.</p><button class="primary" data-action="welcome-login">تسجيل الدخول أو إنشاء حساب</button><button class="secondary" data-action="guest">المتابعة كزائر</button><div class="dev-footer">من المشألي تك · المهندس أحمد المشألي</div></div></section>`}
function searchPage(){const rows=reports.filter(r=>(filterType==='الكل'||(filterType==='مفقودات'?r.type==='lost':r.type==='found'))&&(selectedGovernorate==='كل اليمن'||r.governorate===selectedGovernorate)&&(`${r.title} ${r.city} ${r.governorate} ${r.description}`.includes(searchQuery)));return `<section class="screen">${pageHeader('البحث في البلاغات')}<label class="searchbar"><span class="glass">⌕</span><input id="searchInput" placeholder="ابحث عن اسم الشيء أو المدينة" value="${escapeHTML(searchQuery)}"></label><div class="filters">${['الكل','مفقودات','موجودات'].map(x=>`<button class="chip ${filterType===x?'active':''}" data-filter="${x}">${x}</button>`).join('')}</div><div class="location-pill">📍 ${escapeHTML(selectedGovernorate)} <button class="link-btn" data-action="choose-city">تغيير</button></div><div class="section-head"><h2>${rows.length} بلاغات</h2><span class="note">الأحدث أولاً</span></div><div class="cards">${rows.map(reportCard).join('')||'<div class="empty">لا توجد نتائج مطابقة</div>'}</div></section>`}
function createPage(){return `<section class="screen">${pageHeader('إنشاء بلاغ')}<p class="note">اختر نوع البلاغ، ثم أضف التفاصيل التي تساعد على العثور على الشيء.</p><button class="type-choice lost" data-type="lost"><span class="emoji">🎒</span><span><b>فقدت شيئاً</b><small>أبلغ الآخرين عن شيء فقدته</small></span></button><button class="type-choice found" data-type="found"><span class="emoji">🔎</span><span><b>وجدت شيئاً</b><small>أبلغ عن شيء عثرت عليه</small></span></button></section>`}
function formPage(){return `<section class="screen">${pageHeader('تفاصيل البلاغ','add')}<div class="location-pill">نوع البلاغ: <b>${labelType(draftType)}</b></div><form id="reportForm"><div class="field"><label>اسم الشيء *</label><input name="title" required maxlength="70" placeholder="مثال: هاتف جوال أسود"></div><div class="field"><label>التصنيف</label><select name="category"><option>مقتنيات شخصية</option><option>إلكترونيات</option><option>مفاتيح</option><option>حيوانات</option><option>وثائق وبطاقات</option><option>حقائب</option><option>أخرى</option></select></div><div class="field"><label>الوصف *</label><textarea name="description" required maxlength="500" placeholder="اللون، العلامات المميزة، ومكان العثور أو الفقد"></textarea></div><div class="field"><label>المحافظة *</label><select name="governorate" required>${GOVERNORATES.map((g,i)=>`<option ${i===2?'selected':''}>${escapeHTML(g)}</option>`).join('')}</select></div><div class="field"><label>المدينة أو المنطقة *</label><input name="city" required maxlength="70" placeholder="مثال: المنصورة"></div><div class="field"><label>تاريخ البلاغ</label><input name="dateLabel" type="date"></div><div class="field"><label>صورة للشيء (اختياري)</label><input name="photo" type="file" accept="image/*"><small class="note">تجنب إظهار بيانات شخصية أو بطاقات في الصورة.</small><div id="photoPreview"></div></div><div class="field"><label>رقم للتواصل (اختياري)</label><input name="phone" type="tel" inputmode="tel" maxlength="20" placeholder="يظهر لصاحب البلاغ فقط في النموذج التجريبي"></div><p class="note">النموذج يحفظ البلاغ في هذا المتصفح فقط. لا تكتب رقم هوية أو بيانات مالية أو عنوان المنزل.</p><button class="primary">حفظ البلاغ</button></form></section>`}
function detailPage(){const r=selectedReport||reports[0];if(!r)return `<section class="screen">${pageHeader('تفاصيل البلاغ')}<div class="empty">لم يتم العثور على البلاغ.</div></section>`;return `<section class="screen detail">${pageHeader('تفاصيل البلاغ','search')}<div class="detail-art">${r.photo?`<img src="${r.photo}" alt="صورة البلاغ">`:escapeHTML(r.icon||'📦')}</div><div class="item-foot"><span class="badge ${r.type}">${labelType(r.type)}</span><span>${escapeHTML(r.date||'')}</span><button class="link-btn" data-action="favorite">${favorites.includes(r.id)?'♥ محفوظ':'♡ حفظ'}</button></div><h1>${escapeHTML(r.title)}</h1><div class="meta">📍 ${escapeHTML(r.city||'')}، ${escapeHTML(r.governorate||'')} · ${escapeHTML(r.category||'')}</div><p>${escapeHTML(r.description||'')}</p><div class="contact-card"><b>تواصل بأمان</b><br>تحقق من وصف الشيء قبل ترتيبات الاستلام، ولا تشارك رموز التحقق أو بياناتك المالية.</div>${r.phone?`<a class="primary button-link" href="https://wa.me/${encodeURIComponent(r.phone.replace(/\D/g,''))}" target="_blank" rel="noopener">تواصل مع صاحب البلاغ عبر واتساب</a>`:`<button class="primary" data-action="owner-chat">✉️ راسل صاحب البلاغ</button>`}<button class="secondary full" data-action="share">مشاركة البلاغ</button>${r.mine?`<button class="secondary full danger" data-action="delete-report">حذف بلاغي</button>`:''}</section>`}
function alertsPage(){const own=reports.filter(r=>r.mine&&(!searchQuery||`${r.title} ${r.city}`.includes(searchQuery)));return `<section class="screen">${pageHeader('بلاغاتي')}<div class="section-head"><h2>بلاغاتي (${own.length})</h2><button class="link-btn" data-tab="add">＋ بلاغ جديد</button></div><div class="cards">${own.map(reportCard).join('')||'<div class="empty"><div style="font-size:38px">📋</div><b>لا توجد بلاغات حتى الآن</b><p>اضغط على + لإنشاء أول بلاغ.</p></div>'}</div><div class="section-head"><h2>المحفوظة (${favorites.length})</h2></div><div class="cards">${reports.filter(r=>favorites.includes(r.id)).map(reportCard).join('')||'<p class="note">لم تحفظ أي بلاغ بعد.</p>'}</div></section>`}
function messagesPage(){return `<section class="screen">${pageHeader('الرسائل')}<div class="chat-list"><div class="chat-row" data-action="support"><div class="avatar">🤖</div><div class="chat-info"><b>فريق الدعم الذكي</b><div class="note">مساعد تجريبي لا يحتاج تسجيل دخول</div></div><span class="arrow">‹</span></div>${reports.filter(r=>r.mine).map(r=>`<div class="chat-row" data-action="owner-chat" data-id="${escapeHTML(r.id)}"><div class="avatar">👤</div><div class="chat-info"><b>محادثات البلاغات</b><div class="note">${escapeHTML(r.title)}</div></div><span class="arrow">‹</span></div>`).join('')}<div class="empty">تظهر محادثات أصحاب البلاغات عند تفعيل الخادم. حالياً يفتح التواصل عبر واتساب إذا أضاف المبلّغ رقمه.</div></div></section>`}
function supportPage(){const msgs=chatMessages.filter(m=>m.target==='support');return `<section class="screen">${pageHeader('فريق الدعم الذكي','messages')}<div class="chat-window"><div class="chat-messages" id="chatMessages">${msgs.length?msgs.map(m=>`<div class="bubble ${m.who}">${escapeHTML(m.text)}</div>`).join(''):'<div class="bubble theirs">أهلاً بك! أستطيع إرشادك لإنشاء بلاغ أو البحث في التطبيق. كيف أساعدك؟</div>'}</div><form class="chat-compose" id="chatForm"><input name="message" placeholder="اكتب سؤالك..." autocomplete="off" required><button class="nav-add" aria-label="إرسال">➤</button></form></div><p class="note">الدردشة الآن ردود إرشادية تجريبية. ربط نموذج ذكاء اصطناعي حقيقي يحتاج خدمة خادمية ومفتاح API آمن.</p></section>`}
function accountPage(){return `<section class="screen">${pageHeader('حسابي')}<div class="profile"><div class="avatar">👤</div><h2>${escapeHTML(user?.name||'زائر')}</h2><p>${escapeHTML(user?.email||'تصفّح كزائر')}</p></div>${user?'<div class="contact-card">حساب تجريبي محفوظ محلياً على هذا الجهاز. لا تستخدم كلمة مرور حقيقية في هذا النموذج.</div>':`<div class="signin-box"><h2>مرحباً بك</h2><p class="note">سجّل الدخول التجريبي لحفظ اسمك على هذا الجهاز.</p><button class="primary" data-action="welcome-login">تسجيل الدخول / إنشاء حساب</button><button class="secondary full" data-action="guest">المتابعة كزائر</button></div>`}<div class="stat-row"><div class="stat"><b>${reports.filter(r=>r.mine).length}</b><small>بلاغاتي</small></div><div class="stat"><b>${favorites.length}</b><small>المحفوظة</small></div><div class="stat"><b>٢٢</b><small>محافظة يمنية</small></div></div><div class="settings-list"><div class="settings-row" data-action="search">🔎 <span>استعراض البلاغات</span><span>‹</span></div><div class="settings-row" data-action="support">❔ <span>المساعدة والدعم</span><span>‹</span></div><div class="settings-row" data-action="contact-info">☎️ <span>تواصل مع المشألي تك</span><span>‹</span></div><div class="settings-row" data-action="privacy">🛡️ <span>الخصوصية والاستخدام الآمن</span><span>‹</span></div>${user?'<div class="settings-row" data-action="logout">↪️ <span>تسجيل الخروج</span><span>‹</span></div>':''}</div><div class="dev-footer">المطور والمهندس: أحمد المشألي<br><b>من المشألي تك</b><br><a href="tel:+96777639330" dir="ltr">+967 77639330</a><br><a href="mailto:ahmedalmshali2004@gmail.com">ahmedalmshali2004@gmail.com</a></div></section>`}
function authPage(){return `<section class="screen">${pageHeader(authMode==='register'?'إنشاء حساب':'تسجيل الدخول','account')}<div class="signin-box"><div class="brand center-brand">📍 مفقود</div><h2>${authMode==='register'?'أنشئ حسابك':'أهلاً بعودتك'}</h2><p class="note">دخول تجريبي محلي فقط؛ لا تكتب كلمة مرور تستخدمها في حساب آخر.</p><form id="authForm">${authMode==='register'?'<div class="field"><label>الاسم</label><input name="name" required maxlength="60" autocomplete="name"></div>':''}<div class="field"><label>البريد الإلكتروني</label><input name="email" type="email" required autocomplete="email"></div><div class="field"><label>كلمة مرور تجريبية</label><input name="password" type="password" required minlength="6" autocomplete="off"></div><button class="primary">${authMode==='register'?'إنشاء حساب تجريبي':'دخول تجريبي'}</button></form><button class="link-btn full" data-action="toggle-auth">${authMode==='register'?'لديك حساب؟ سجّل الدخول':'مستخدم جديد؟ أنشئ حساباً'}</button><p class="note">قبل النشر العام يجب ربط تسجيل الدخول بخدمة آمنة وإضافة سياسة خصوصية.</p></div></section>`}
function cityPage(){return `<section class="screen">${pageHeader('اختر المحافظة','search')}<div class="settings-list"><button class="settings-row" data-governorate="كل اليمن">كل اليمن <span>‹</span></button>${[...new Set(GOVERNORATES)].map(g=>`<button class="settings-row" data-governorate="${escapeHTML(g)}">${escapeHTML(g)} <span>‹</span></button>`).join('')}</div></section>`}
function adminPage(){const all=reports.filter(r=>!r.id.startsWith('seed-'));return `<section class="screen">${pageHeader('إدارة البلاغات','account')}<div class="contact-card">لوحة إدارة محلية للتجربة فقط؛ صلاحيات المشرف تتطلب خادماً وتسجيل دخول آمن.</div><div class="cards">${all.map(r=>`${reportCard(r)}<button class="secondary full danger" data-delete-id="${escapeHTML(r.id)}">حذف البلاغ</button>`).join('')||'<div class="empty">لا توجد بلاغات محلية لمراجعتها.</div>'}</div></section>`}
function render(){const pages={welcome:welcomePage,home:homePage,search:searchPage,add:createPage,form:formPage,detail:detailPage,alerts:alertsPage,messages:messagesPage,chat:supportPage,account:accountPage,login:authPage,city:cityPage,admin:adminPage};view.innerHTML=(pages[screen]||homePage)();const onboarding=screen==='welcome'||screen==='login';header.style.display=screen==='welcome'?'none':'flex';nav.style.display=onboarding?'none':'flex';if(screen==='chat'){const el=document.getElementById('chatMessages');if(el)el.scrollTop=el.scrollHeight}}
function replyToSupport(question){const q=question.toLowerCase();if(q.includes('بلاغ')||q.includes('فقد')||q.includes('وجد'))return 'لإنشاء بلاغ اضغط زر + أسفل الشاشة، واختر «فقدت شيئاً» أو «وجدت شيئاً»، ثم أضف الوصف والمحافظة والمنطقة.';if(q.includes('بحث')||q.includes('ابحث'))return 'افتح البحث من الشريط السفلي، واكتب اسم الشيء أو المدينة، ثم صفِّ النتائج إلى مفقودات أو موجودات.';if(q.includes('محافظ')||q.includes('مدينة'))return 'التطبيق يضم قائمة المحافظات اليمنية. من البحث اضغط «تغيير» لاختيار المحافظة.';if(q.includes('تواصل')||q.includes('دعم'))return 'للتواصل مع المطور: +96777639330 أو ahmedalmshali2004@gmail.com.';return 'أقدر أساعدك في إنشاء بلاغ أو البحث عن شيء. اكتب سؤالك عن إحدى هاتين الخطوتين.'}
function compressImage(file){return new Promise(resolve=>{if(!file||!file.type.startsWith('image/'))return resolve('');const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const canvas=document.createElement('canvas'),scale=Math.min(1,900/Math.max(img.width,img.height));canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.72))};img.onerror=()=>resolve('');img.src=reader.result};reader.onerror=()=>resolve('');reader.readAsDataURL(file)})}
function normalizeDate(date){if(!date)return 'اليوم';try{return new Intl.DateTimeFormat('ar-YE',{day:'numeric',month:'long',year:'numeric'}).format(new Date(`${date}T12:00:00`))}catch{return 'اليوم'}}

document.addEventListener('click',event=>{
 const tab=event.target.closest('[data-tab]');if(tab){goTab(tab.dataset.tab);return}
 const filter=event.target.closest('[data-filter]');if(filter){filterType=filter.dataset.filter;render();return}
 const row=event.target.closest('[data-item]');if(row){selectedReport=reports.find(r=>String(r.id)===row.dataset.item);showScreen('detail');return}
 const gov=event.target.closest('[data-governorate]');if(gov){selectedGovernorate=gov.dataset.governorate;screen='search';render();return}
 const type=event.target.closest('[data-type]');if(type){draftType=type.dataset.type;showScreen('form');return}
 const del=event.target.closest('[data-delete-id]');if(del){reports=reports.filter(r=>String(r.id)!==del.dataset.deleteId);persist();render();notify('تم حذف البلاغ من هذا الجهاز');return}
 const back=event.target.closest('[data-go]');if(back){screen=back.dataset.go;render();return}
 const action=event.target.closest('[data-action]')?.dataset.action;if(!action)return;
 switch(action){
  case'create-lost':draftType='lost';showScreen('form');break;
  case'create-found':draftType='found';showScreen('form');break;
  case'search':searchQuery='';screen='search';render();break;
  case'choose-city':screen='city';render();break;
  case'welcome-login':authMode='login';screen='login';render();break;
  case'guest':user={name:'زائر',email:''};localStorage.setItem('mafqood.user',JSON.stringify(user));screen='home';render();notify('تتابع الآن كزائر');break;
  case'toggle-auth':authMode=authMode==='login'?'register':'login';render();break;
  case'logout':localStorage.removeItem('mafqood.user');user=null;screen='welcome';render();notify('تم تسجيل الخروج');break;
  case'support':chatTarget='support';showScreen('chat');break;
  case'contact-info':notify('الهاتف +96777639330 · البريد ahmedalmshali2004@gmail.com');break;
  case'privacy':notify('لا تنشر بيانات الهوية أو موقع المنزل أو معلومات مالية.');break;
  case'favorite':if(selectedReport){favorites=favorites.includes(selectedReport.id)?favorites.filter(id=>id!==selectedReport.id):[...favorites,selectedReport.id];persist();render();notify(favorites.includes(selectedReport.id)?'أضيف إلى المحفوظات':'أزيل من المحفوظات')}break;
  case'owner-chat':if(selectedReport?.phone){window.open(`https://wa.me/${selectedReport.phone.replace(/\D/g,'')}`,'_blank','noopener')}else notify('لم يضف صاحب البلاغ رقم تواصل.');break;
  case'delete-report':if(selectedReport?.mine){reports=reports.filter(r=>r.id!==selectedReport.id);persist();screen='alerts';render();notify('حُذف البلاغ من هذا الجهاز')}break;
  case'share':if(navigator.share)navigator.share({title:selectedReport?.title||'مفقود',text:`بلاغ ${selectedReport?.title||''} في تطبيق مفقود`,url:location.href}).catch(()=>{});else if(navigator.clipboard)navigator.clipboard.writeText(location.href).then(()=>notify('نُسخ رابط التطبيق'));else notify('انسخ رابط الصفحة لمشاركتها');break;
  case'notifications':notify('لا توجد تنبيهات جديدة');break;
  case'menu':screen='account';render();break;
 }
});
document.addEventListener('input',event=>{if(event.target.id==='homeSearch'||event.target.id==='searchInput'){searchQuery=event.target.value;const id=event.target.id,pos=event.target.selectionStart;render();const next=document.getElementById(id);if(next){next.focus();next.setSelectionRange(pos,pos)}}});
document.addEventListener('change',async event=>{if(event.target.name==='photo'){const image=await compressImage(event.target.files?.[0]);const preview=document.getElementById('photoPreview');if(preview&&image)preview.innerHTML=`<img class="photo-preview" src="${image}" alt="معاينة الصورة">`}});
document.addEventListener('submit',async event=>{
 if(event.target.id==='reportForm'){event.preventDefault();const form=event.target,data=new FormData(form);const photo=await compressImage(form.elements.photo.files?.[0]);const report={id:`r-${Date.now()}`,title:String(data.get('title')).trim(),type:draftType,icon:draftType==='lost'?'🎒':'🔎',governorate:String(data.get('governorate')),city:String(data.get('city')).trim(),date:normalizeDate(data.get('dateLabel')),description:String(data.get('description')).trim(),owner:user?.name||'زائر',phone:String(data.get('phone')||'').trim(),photo,category:String(data.get('category')),mine:true};reports.unshift(report);persist();selectedReport=report;screen='detail';render();notify('تم حفظ البلاغ على هذا الجهاز');return}
 if(event.target.id==='authForm'){event.preventDefault();const data=new FormData(event.target),email=String(data.get('email')).trim(),name=String(data.get('name')||email.split('@')[0]).trim();user={name,email};localStorage.setItem('mafqood.user',JSON.stringify(user));screen='home';render();notify('تم الدخول التجريبي؛ الحساب محلي على هذا الجهاز');return}
 if(event.target.id==='chatForm'){event.preventDefault();const data=new FormData(event.target),question=String(data.get('message')||'').trim();if(!question)return;chatMessages.push({who:'mine',text:question,target:'support'});chatMessages.push({who:'theirs',text:replyToSupport(question),target:'support'});persist();render()}
});
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
render();
