const cities=['عدن','صنعاء','تعز','الحديدة','المكلا','سيئون','إب','ذمار','لحج','أبين','شبوة','مأرب','صعدة','حجة','عمران','الضالع','البيضاء','الجوف','المحويت','ريمة','سقطرى','أمانة العاصمة'];
const seed=[
 {id:1,title:'هاتف جوال أسود',type:'lost',icon:'📱',city:'عدن',area:'المنصورة',date:'منذ ساعتين',desc:'هاتف أسود بغطاء شفاف، فُقد بالقرب من سوق المنصورة. لمن عثر عليه نرجو التواصل.'},
 {id:2,title:'مفتاح سيارة',type:'found',icon:'🔑',city:'تعز',area:'وسط المدينة',date:'منذ ٤ ساعات',desc:'تم العثور على مفتاح سيارة قرب الشارع الرئيسي. يرجى وصف العلامة المميزة للتأكد.'},
 {id:3,title:'محفظة بنية',type:'found',icon:'👛',city:'صنعاء',area:'حي النخيل',date:'منذ ٦ ساعات',desc:'محفظة بنية تحتوي على بطاقات. لا نعرض تفاصيلها حفاظاً على الخصوصية.'},
 {id:4,title:'حقيبة يد صغيرة',type:'lost',icon:'👜',city:'المكلا',area:'السوق القديم',date:'أمس',desc:'حقيبة صغيرة لونها كحلي فُقدت في السوق القديم.'}
];
let reports=JSON.parse(localStorage.getItem('mafqood.reports')||'null')||seed;
let activeTab='home',screen='home',query='',filter='الكل',selectedCity='كل مدن اليمن',typeDraft='lost',selected=null,chat=[],signedIn=localStorage.getItem('mafqood.user')||'',toastTimer;
const view=document.querySelector('#view');
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const save=()=>localStorage.setItem('mafqood.reports',JSON.stringify(reports));
function notify(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2300)}
function setTab(t){activeTab=t;document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));screen=t;render()}
function top(title,back='home'){return `<div class="page-title"><button class="back" data-go="${back}">›</button><h1>${title}</h1><span></span></div>`}
function itemCard(r){return `<article class="item-card" data-item="${r.id}"><div class="item-art">${r.icon}</div><div class="item-info"><b>${esc(r.title)}</b><p>${esc(r.area)}، ${esc(r.city)}</p><div class="item-foot"><span class="badge ${r.type}">${r.type==='lost'?'مفقود':'موجود'}</span><span>• ${esc(r.date)}</span></div></div><span class="arrow">‹</span></article>`}
function home(){let list=reports.filter(r=>(filter==='الكل'||(filter==='مفقودات'?r.type==='lost':r.type==='found'))&&(`${r.title} ${r.city} ${r.area}`.includes(query)));return `<section class="screen"><p class="greeting">مرحباً ${signedIn?esc(signedIn):'بك'} 👋</p><h1 class="headline">خلّينا نساعد بعض</h1><label class="searchbar"><span class="glass">⌕</span><input id="homeSearch" placeholder="ابحث في البلاغات..." value="${esc(query)}"/><span>⚲</span></label><div class="hero-grid"><button class="hero-card lost" data-action="create-lost"><span class="emoji">🎒</span><b>فقدت شيئاً</b><small>أبلغ الآخرين عنه</small></button><button class="hero-card found" data-action="create-found"><span class="emoji">🔎</span><b>وجدت شيئاً</b><small>ساعد في إعادته</small></button></div><div class="callout" data-action="open-search"><span class="circle">⌕</span><span><b>ابحث في البلاغات</b><small>تصفّح المفقودات والموجودات في اليمن</small></span><span class="arrow">‹</span></div><div class="section-head"><h2>أحدث البلاغات</h2><button class="link-btn" data-action="open-search">عرض الكل</button></div><div class="filters">${['الكل','مفقودات','موجودات'].map(x=>`<button class="chip ${filter===x?'active':''}" data-filter="${x}">${x}</button>`).join('')}</div><div class="cards">${list.length?list.slice(0,5).map(itemCard).join(''):'<div class="empty">لا توجد بلاغات مطابقة. جرّب كلمة أخرى.</div>'}</div><div class="dev-footer">من تطوير المهندس أحمد المشألي<br/>المشألي تك</div></section>`}
function searchPage(){let list=reports.filter(r=>(filter==='الكل'||(filter==='مفقودات'?r.type==='lost':r.type==='found'))&&(selectedCity==='كل مدن اليمن'||r.city===selectedCity)&&(`${r.title} ${r.city} ${r.area}`.includes(query)));return `<section class="screen">${top('البحث في البلاغات')}<label class="searchbar"><span class="glass">⌕</span><input id="searchInput" placeholder="ابحث عن شيء، مدينة أو منطقة" value="${esc(query)}"/></label><div class="filters">${['الكل','مفقودات','موجودات'].map(x=>`<button class="chip ${filter===x?'active':''}" data-filter="${x}">${x}</button>`).join('')}</div><div class="location-pill">📍 ${esc(selectedCity)} <span style="float:left;cursor:pointer" data-action="city">تغيير</span></div><div class="section-head"><h2>${list.length} بلاغات</h2><span class="note">الأحدث أولاً</span></div><div class="cards">${list.map(itemCard).join('')||'<div class="empty">لا توجد نتائج حالياً</div>'}</div></section>`}
function createPage(){return `<section class="screen">${top('إنشاء بلاغ')}<p class="note">اختر نوع البلاغ، ثم أدخل التفاصيل التي تساعد الآخرين على التعرّف على الشيء.</p><button class="type-choice lost" data-type="lost"><span class="emoji">🎒</span><span><b>فقدت شيئاً</b><small>أبلغ عن شيء مفقود</small></span></button><button class="type-choice found" data-type="found"><span class="emoji">🔎</span><span><b>وجدت شيئاً</b><small>أبلغ عن شيء عثرت عليه</small></span></button></section>`}
function formPage(){return `<section class="screen">${top('تفاصيل البلاغ','add')}<div class="location-pill">نوع البلاغ: <b>${typeDraft==='lost'?'مفقود':'موجود'}</b> <span style="float:left" data-go="add">تغيير</span></div><form id="reportForm"><div class="field"><label>اسم الشيء *</label><input name="title" required maxlength="60" placeholder="مثال: هاتف جوال أسود"/></div><div class="field"><label>وصف يساعد على التعرّف عليه *</label><textarea name="desc" required maxlength="400" placeholder="اذكر اللون أو العلامة المميزة، وتجنب نشر معلومات حساسة"></textarea></div><div class="field"><label>المدينة *</label><select name="city" required>${cities.map(c=>`<option>${c}</option>`).join('')}</select></div><div class="field"><label>المنطقة أو الحي</label><input name="area" maxlength="60" placeholder="مثال: المنصورة"/></div><div class="field"><label>وسيلة التواصل (اختياري)</label><input name="contact" maxlength="80" placeholder="رقم أو بريد للتواصل معك مباشرة"/></div><p class="note">لا تضع رقم الهوية أو بيانات مالية أو عنوان المنزل في وصف البلاغ.</p><button class="primary">نشر البلاغ</button></form></section>`}
function detailPage(){const r=selected||reports[0];return `<section class="screen detail">${top('تفاصيل البلاغ','search')}<div class="detail-art">${r.icon}</div><div class="item-foot"><span class="badge ${r.type}">${r.type==='lost'?'مفقود':'موجود'}</span><span>${esc(r.date)}</span></div><h1>${esc(r.title)}</h1><div class="meta">📍 ${esc(r.city)}، ${esc(r.area)}</div><p>${esc(r.desc)}</p><div class="contact-card"><b>تواصل بأمان</b><br/>لا تشارك رمز تحقق أو بيانات حساسة. تحقق من وصف الشيء قبل ترتيب الاستلام.</div><button class="primary" data-action="contact">✉️ تواصل مع صاحب البلاغ</button><button class="secondary" style="width:100%;margin-top:10px" data-action="share">مشاركة البلاغ</button></section>`}
function messages(){return `<section class="screen">${top('الرسائل')}<div class="chat-list"><div class="chat-row" data-action="support"><div class="avatar">🤖</div><div><b>فريق الدعم الذكي</b><div class="note">اسأل عن استخدام التطبيق أو بلاغك</div></div><span class="arrow">‹</span></div><div class="empty">ستظهر هنا محادثاتك مع أصحاب البلاغات.</div></div></section>`}
function chatPage(){return `<section class="screen">${top('فريق الدعم الذكي','messages')}<div class="chat-window"><div class="chat-messages" id="chatMessages">${chat.length?chat.map(m=>`<div class="bubble ${m.who}">${esc(m.text)}</div>`).join(''):'<div class="bubble theirs">أهلاً بك! أنا مساعد مفقود. أستطيع إرشادك لاستخدام التطبيق، البحث عن بلاغ، أو إنشاء بلاغ جديد. كيف أساعدك؟</div>'}</div><form class="chat-compose" id="chatForm"><input name="message" placeholder="اكتب رسالتك..." autocomplete="off"/><button class="nav-add" style="width:44px;height:44px;font-size:20px">➤</button></form></div><p class="note">هذا رد تجريبي محلي، وليس اتصالاً بخدمة ذكاء اصطناعي مباشرة.</p></section>`}
function alerts(){const own=reports.filter(r=>r.mine);const content=own.length?own.map(itemCard).join(''):`<div class="empty"><div style="font-size:36px">📋</div><b>لا توجد بلاغات بعد</b><p>أنشئ بلاغاً لمساعدة الآخرين في اليمن.</p><button class="primary" data-tab="add">إنشاء بلاغ</button></div>`;return `<section class="screen">${top('بلاغاتي')}<div class="cards">${content}</div></section>`}
function account(){return `<section class="screen">${top('حسابي')}<div class="profile"><div class="avatar">👤</div><h2>${signedIn?esc(signedIn):'زائر مفقود'}</h2><p>${signedIn?'تم تسجيل الدخول على هذا الجهاز':'سجّل الدخول لمتابعة بلاغاتك ورسائلك'}</p></div>${!signedIn?`<div class="signin-box"><h2>مرحباً بعودتك</h2><p class="note">أنشئ حساباً أو سجّل الدخول لتتمكن من حفظ بلاغاتك والتواصل.</p><button class="primary" data-action="login">تسجيل الدخول / إنشاء حساب</button><button class="secondary" style="width:100%;margin-top:10px" data-action="guest">المتابعة كزائر</button></div>`:''}<div class="stat-row"><div class="stat"><b>${reports.filter(r=>r.mine).length}</b><small>بلاغاتي</small></div><div class="stat"><b>٠</b><small>المحفوظة</small></div><div class="stat"><b>٢٢</b><small>منطقة يمنية</small></div></div><div class="settings-list"><div class="settings-row" data-action="open-search">🔎 <span>استعراض البلاغات</span><span>‹</span></div><div class="settings-row" data-action="support">❔ <span>المساعدة والدعم</span><span>‹</span></div><div class="settings-row" data-action="contact-info">☎️ <span>تواصل مع المشألي تك</span><span>‹</span></div>${signedIn?'<div class="settings-row" data-action="logout">↪️ <span>تسجيل الخروج</span><span>‹</span></div>':''}</div><div class="dev-footer">المطور والمهندس: أحمد المشألي<br/><b>من المشألي تك</b><br/><a href="tel:+96777639330" dir="ltr">+967 77639330</a> · <a href="mailto:ahmedalmshali2004@gmail.com">ahmedalmshali2004@gmail.com</a></div></section>`}
function loginPage(){return `<section class="screen">${top('تسجيل الدخول','account')}<div class="signin-box"><div class="brand" style="justify-content:center;margin-bottom:18px">● مفقود</div><h2>أهلاً بك في مفقود</h2><p class="note">هذه واجهة تجريبية. الدخول هنا محفوظ على جهازك فقط، ولا ينشئ حساباً حقيقياً بعد.</p><form id="loginForm"><div class="field"><label>الاسم</label><input name="name" required placeholder="اكتب اسمك" autocomplete="name"/></div><div class="field"><label>البريد الإلكتروني</label><input name="email" type="email" required placeholder="name@example.com" autocomplete="email"/></div><div class="field"><label>كلمة المرور</label><input name="password" type="password" required minlength="6" placeholder="٦ أحرف على الأقل" autocomplete="new-password"/></div><button class="primary">دخول</button></form><p class="note">في النسخة المنشورة يجب استخدام خدمة آمنة لتسجيل الحسابات، والتحقق من البريد، واستعادة كلمة المرور.</p></div></section>`}
function cityPage(){return `<section class="screen">${top('اختر المدينة','search')}<div class="cards">${cities.map(c=>`<button class="settings-row" data-city="${c}">${c}<span>‹</span></button>`).join('')}</div></section>`}
function render(){const pages={home,search:searchPage,add:createPage,form:formPage,detail:detailPage,messages,chat:chatPage,alerts,account,login:loginPage,city:cityPage};view.innerHTML=(pages[screen]||home)();if(screen==='chat'){const el=document.querySelector('#chatMessages');el.scrollTop=el.scrollHeight}}
function go(s){screen=s;render()}
function assistantReply(q){const t=q.toLowerCase();if(t.includes('بلاغ')||t.includes('فقد'))return 'لإنشاء بلاغ اضغط زر + أسفل الشاشة، ثم اختر «فقدت شيئاً» أو «وجدت شيئاً» واملأ التفاصيل والمدينة.';if(t.includes('بحث')||t.includes('ابحث'))return 'اذهب إلى البحث من الرئيسية، واكتب اسم الشيء أو المدينة، ثم اختر مفقودات أو موجودات.';if(t.includes('تواصل')||t.includes('دعم'))return 'يمكنك التواصل مع فريق المشألي تك عبر +967 77639330 أو ahmedalmshali2004@gmail.com.';return 'وصلتني رسالتك. هذا مساعد تجريبي؛ للحصول على إجابة دقيقة اذكر هل تحتاج مساعدة في إنشاء بلاغ أو البحث عن شيء.'}
document.addEventListener('click',e=>{const tab=e.target.closest('[data-tab]');if(tab){setTab(tab.dataset.tab);return}const f=e.target.closest('[data-filter]');if(f){filter=f.dataset.filter;render();return}const item=e.target.closest('[data-item]');if(item){selected=reports.find(x=>x.id===Number(item.dataset.item));go('detail');return}const choice=e.target.closest('[data-type]');if(choice){typeDraft=choice.dataset.type;go('form');return}const city=e.target.closest('[data-city]');if(city){selectedCity=city.dataset.city;filter='الكل';notify('تم اختيار '+selectedCity);go('search');return}const back=e.target.closest('[data-go]');if(back){go(back.dataset.go);return}const a=e.target.closest('[data-action]')?.dataset.action;if(!a)return;switch(a){case'create-lost':typeDraft='lost';go('form');break;case'create-found':typeDraft='found';go('form');break;case'open-search':go('search');break;case'support':go('chat');break;case'login':go('login');break;case'guest':notify('تتابع الآن كزائر');break;case'logout':signedIn='';localStorage.removeItem('mafqood.user');render();notify('تم تسجيل الخروج');break;case'city':go('city');break;case'contact':go('chat');chat.push({who:'theirs',text:'مرحباً، اكتب لصاحب البلاغ رسالة للتنسيق بأمان.'});break;case'share':if(navigator.share)navigator.share({title:selected?.title||'مفقود',text:`بلاغ ${selected?.title||''} في تطبيق مفقود`}).catch(()=>{});else notify('يمكنك نسخ رابط البلاغ بعد ربط التطبيق بالخادم');break;case'contact-info':notify('+967 77639330 · ahmedalmshali2004@gmail.com');break;case'notifications':notify('لا توجد تنبيهات جديدة');break;case'menu':notify('من القائمة: البحث والبلاغات والدعم');break;}}
);
document.addEventListener('input',e=>{if(e.target.id==='homeSearch'||e.target.id==='searchInput'){query=e.target.value;const pos=e.target.selectionStart;render();const n=document.querySelector('#'+e.target.id);n?.focus();n?.setSelectionRange(pos,pos)}});
document.addEventListener('submit',e=>{if(e.target.id==='reportForm'){e.preventDefault();const d=new FormData(e.target);const r={id:Date.now(),title:d.get('title'),desc:d.get('desc'),city:d.get('city'),area:d.get('area')||'المدينة',type:typeDraft,icon:typeDraft==='lost'?'🎒':'🔎',date:'الآن',mine:true};reports.unshift(r);save();selected=r;go('detail');notify('تم نشر البلاغ على هذا الجهاز');return}if(e.target.id==='loginForm'){e.preventDefault();const d=new FormData(e.target);signedIn=d.get('name');localStorage.setItem('mafqood.user',signedIn);go('account');notify('تم الدخول التجريبي');return}if(e.target.id==='chatForm'){e.preventDefault();const d=new FormData(e.target),q=String(d.get('message')||'').trim();if(!q)return;chat.push({who:'mine',text:q});chat.push({who:'theirs',text:assistantReply(q)});render()}});
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
render();
